# Generated by Django 4.0.2 on 2022-03-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=70)),
                ('college_name', models.CharField(max_length=70)),
                ('Specialisation', models.CharField(max_length=70)),
                ('degree', models.CharField(max_length=70)),
                ('internship', models.CharField(max_length=70)),
                ('phoneNo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
    ]
